name: magical_book
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8


  #UI libraries
  gap: ^3.0.1
  flutter_screenutil: ^5.9.0

  # State Management
  flutter_riverpod: ^2.6.1
  
  # Navigation
  go_router: ^14.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/banglaChora/
    - assets/images/fruits/
    - assets/images/flowers/
    - assets/images/ritu/
    - assets/images/rhymes/
    - assets/images/bodyParts/
    - assets/images/animal/
    - assets/images/birds/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # Custom fonts
  fonts:
    - family: Kalpurush
      fonts:
        - asset: assets/fonts/Kalpurush.ttf
